# Generated by Django 3.0.6 on 2020-05-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^[ a-zA-Z]*$', 'Only space separate English letters are allowed.')]),
        ),
    ]
