# Generated by Django 3.0.6 on 2020-05-30 09:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=85, size=[300, 300], upload_to='profile_pics', verbose_name='profile_pic'),
        ),
    ]
